version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: simple-todo-postgres
    restart: unless-stopped
    ports:
      - "9001:5432"
    environment:
      POSTGRES_DB: simple_todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d simple_todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local 